[package]
name = "sso"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"]  }
serde_json = "1.0.140"
serde_with = { version = "3.12.0", features = ["chrono"] }
