[package]
name = "sso"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
chrono = "0.4.40"
maud = { version = "0.27.0", features = ["actix-web"] }
rand = "0.9.0"
regex = "1.11.1"
