[package]
name = "sso2"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
chrono = "0.4.40"
rand = "0.9.0"
rand_distr = "0.5.1"
rusqlite = { version = "0.34.0", features = ["bundled", "chrono"] }
